name: 'pr-bot'
description: 'A GitHub Action that automatically approves PR that meets certain requirement'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
    default: ${{ secrets.GITHUB_TOKEN }}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github_token }}
