name: 'pr-bot'
description: 'A GitHub Action that automatically approves PR that meets certain requirement'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
    default: ${{ github.token }}
runs:
  using: 'docker'
  image: 'Dockerfile'

