name: PR bot GitHub APP

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled, review_requested, review_request_removed, assigned, unassigned, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Invoke local action # for testing workflow change in the feature branch
        uses: ./ # uses the local action defined by action.yml in the root of the repository
        with:
          github_token: ${{ secrets.PR_BOT_TOKEN }}

      - name: PR Bot
        uses: marqeta/pr-bot-cli@main
        with:
          github_token: ${{ secrets.PR_BOT_TOKEN }}
