name: PR bot GitHub APP

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled, review_requested, review_request_removed, assigned, unassigned, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for opening this pull request! PR Bot will auto-approve if it can.'
            })

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Invoke local action # for testing workflow change in the feature branch
        uses: ./ # uses the local action defined by action.yml in the root of the repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Invoke action
        uses: marqeta/pr-bot-cli@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
